### ISSUE TITLE
Problem on Mac Silicon?

### ISSUE THREAD

**Issue by nikhansen** [LasseR15/bibox-to-pdf#9]
I tried using your tool but it doesn't seem to work for me - or I'm missing a point. 
Im running it on a M2 Mac and im a Docker Newbie tbh. Entering the Docker CLI command its saying "WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
Usage: main.py [OPTIONS] USERNAME PASSWORD BOOK_ID
Try 'main.py --help' for help.
╭─ Error ────────────────────────────────────────────────────────────────────────────────────────────╮
│ Invalid value for 'BOOK_ID': '{5817}' is not a valid integer.    
Do you know how to deal with this? Docker Compose isn't working for me aswell.

**Comment by LasseR15** [comment]
Hi nikhansen,
did you run the command without the curly brackets? So for example like this?:
`docker run --rm -it -v ./books:/app/output/books ghcr.io/lasser15/bibox-to-pdf:latest 'my_username' 'my_passwd' 5817`

I don't know how Docker or specifically this container runs on Apple's M chips, but I would assume that Docker should run broadly the same on any hardware (only the container image isn't currently built for ARM, but since this is just a warning message, it might still work perfectly fine).

**Comment by nikhansen** [comment]
well... it was my fault since I used the curly brackets. thanks for your work!!
